[workspace]
resolver = "2"
members = ["pong", "ping", "pong-api", "blinky", "display", "uart-echo"]

[workspace.dependencies]
userlib = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
hubris-task-slots = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
hubris-notifications = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
hubris-build = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
hubris-build-util = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
idyll_runtime = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }
drv-stm32xx-sys-api = { git = "https://github.com/wnj/exhubris", rev = "f6e94156771bc4a62e914d87dbdaee1d9169e2be" }

[profile.release]
debug = true
lto = true
