[package]
name = "ping"
version = "0.1.0"
edition = "2021"

[dependencies]
drv-stm32xx-sys-api.workspace = true
hubris-notifications.workspace = true
hubris-task-slots.workspace = true
pong-api = { version = "0.1.0", path = "../pong-api" }
userlib = { workspace = true, features = ["no-panic"] }
