[package]
name = "pong"
version = "0.1.0"
edition = "2021"

[dependencies]
hubpack = "0.1.2"
idyll_runtime.workspace = true
userlib = {workspace = true, features = ["no-panic"]}

[build-dependencies]
hubris-build.workspace = true
